// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(WebApplication1Context))]
    partial class WebApplication1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Desk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("HeightUpDown");

                    b.Property<int>("Material");

                    b.Property<int>("NumDrawers");

                    b.Property<decimal>("WidthUpDown");

                    b.HasKey("ID");

                    b.ToTable("Desk");
                });

            modelBuilder.Entity("WebApplication1.Models.DeskQuote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName");

                    b.Property<int?>("DeskID");

                    b.Property<decimal>("Quote");

                    b.Property<DateTime>("QuoteDate");

                    b.Property<decimal>("ShippingCost");

                    b.Property<int>("ShippingDays");

                    b.Property<decimal>("StructureCost");

                    b.Property<decimal>("SurfaceCost");

                    b.HasKey("ID");

                    b.HasIndex("DeskID");

                    b.ToTable("DeskQuote");
                });

            modelBuilder.Entity("WebApplication1.Models.Link", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeskID");

                    b.HasKey("ID");

                    b.HasIndex("DeskID");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("WebApplication1.Models.DeskQuote", b =>
                {
                    b.HasOne("WebApplication1.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskID");
                });

            modelBuilder.Entity("WebApplication1.Models.Link", b =>
                {
                    b.HasOne("WebApplication1.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskID");
                });
#pragma warning restore 612, 618
        }
    }
}
